CXX = g++
CXXFLAGS = -std=c++11 -I./include -I$(VCPKG_ROOT)/installed/x64-windows/include
LDFLAGS = -L$(VCPKG_ROOT)/installed/x64-windows/lib -lgtest -lgtest_main -lpthread
SRC_DIR = src
OBJ_DIR = bin
CONFIG_DIR = config
TEST_DIR = src/tests
SRC_FILES = $(wildcard $(SRC_DIR)/*.cpp)
OBJ_FILES = $(SRC_FILES:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
TEST_FILES = $(wildcard $(TEST_DIR)/*.cpp)
TEST_OBJ_FILES = $(TEST_FILES:$(TEST_DIR)/%.cpp=$(OBJ_DIR)/%.o)
EXECUTABLE = $(OBJ_DIR)/evaluador

all: $(EXECUTABLE) tests

$(EXECUTABLE): $(OBJ_FILES)
	$(CXX) $(OBJ_FILES) -o $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: $(TEST_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

tests: $(TEST_OBJ_FILES) $(OBJ_FILES)
	$(CXX) $(OBJ_DIR)/test_evaluador.o $(OBJ_FILES) $(LDFLAGS) -o $(OBJ_DIR)/test_evaluador
	$(CXX) $(OBJ_DIR)/test_historial.o $(OBJ_FILES) $(LDFLAGS) -o $(OBJ_DIR)/test_historial
	$(CXX) $(OBJ_DIR)/test_memoria.o $(OBJ_FILES) $(LDFLAGS) -o $(OBJ_DIR)/test_memoria
	$(CXX) $(OBJ_DIR)/test_configuracion.o $(OBJ_FILES) $(LDFLAGS) -o $(OBJ_DIR)/test_configuracion

clean:
	rm -rf $(OBJ_DIR)/*.o $(EXECUTABLE) $(OBJ_DIR)/test_*

.PHONY: all clean tests
